theme: jekyll-theme-minimal
title: MicrobeDB.jp
description: How to use MicrobeDB.jp
#logo: https://microbedbjp.github.io/document/mdb_logo.png
logo: /mdb_logo.png

#baseurl: "https://microbedbjp.github.io/document"

markdown: kramdown
